name: jupyterlite-xeus
channels:
  # https://repo.mamba.pm/emscripten-forge
  - https://repo.prefix.dev/emscripten-forge-dev
  # conda-forge
dependencies:
  - xeus-python
  # xeus-javascript
  - xeus-cpp
  # xeus-lua
